### ISSUE TITLE
Unable to post new event

### ISSUE THREAD

**Issue by gh-xj** [Simonl07/acuppa-rn-public#1]
Your Acuppa account email (if apply): <email>

### Describe the bug
Postman unable to post new event

### To Reproduce
1. Go to postman/org 'new event'
2. Click on 'send'
3. return error 400: "Bad Request" with the message: "SON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 9, column: 26] (through reference chain: zoog.prototype.model.NewEvent[\"address\"]->java.util.LinkedHashMap[\"address_components\"])"

### Screenshots

![image](https://user-images.githubusercontent.com/46443118/82393278-f2fdd900-9a13-11ea-873d-cc3906016aac.png)

**Comment by Simonl07** [comment]
@xj-m Check the latest postman for updated new event JSON

**Comment by Simonl07** [comment]
Close issue if worked
